apiVersion: apps/v1
kind: Deployment
metadata:
  name: may-k8s-cicd
labels:
  batch: may
  app: java
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: mymaven
          image: pkw0301/myadockercicd:latest
          imagePullPolicy: Always
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  selector:
    app: maven
  ports:
    - port: 80
  type: NodePort
